// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: i9bwxGcVwvFmrCRHUfpYDk
// Component: q9XlE3bse9lFTO
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_furn_e_commerce.module.css"; // plasmic-import: i9bwxGcVwvFmrCRHUfpYDk/projectcss
import * as sty from "./PlasmicRatings.module.css"; // plasmic-import: q9XlE3bse9lFTO/css

import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: gEuNl4k917hjI2/icon

export type PlasmicRatings__VariantMembers = {
  stars: "zero" | "one" | "two" | "three" | "four" | "five";
};

export type PlasmicRatings__VariantsArgs = {
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
};

type VariantPropType = keyof PlasmicRatings__VariantsArgs;
export const PlasmicRatings__VariantProps = new Array<VariantPropType>("stars");

export type PlasmicRatings__ArgsType = {
  numReviews?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRatings__ArgsType;
export const PlasmicRatings__ArgProps = new Array<ArgPropType>("numReviews");

export type PlasmicRatings__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultRatingsProps {
  numReviews?: React.ReactNode;
  stars?: SingleChoiceArg<"zero" | "one" | "two" | "three" | "four" | "five">;
  className?: string;
}

function PlasmicRatings__RenderFunc(props: {
  variants: PlasmicRatings__VariantsArgs;
  args: PlasmicRatings__ArgsType;
  overrides: PlasmicRatings__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <p.Stack
      as={"div"}
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root, {
        [sty.root__stars_five]: hasVariant(variants, "stars", "five"),
        [sty.root__stars_four]: hasVariant(variants, "stars", "four"),
        [sty.root__stars_one]: hasVariant(variants, "stars", "one"),
        [sty.root__stars_three]: hasVariant(variants, "stars", "three"),
        [sty.root__stars_two]: hasVariant(variants, "stars", "two"),
        [sty.root__stars_zero]: hasVariant(variants, "stars", "zero")
      })}
    >
      <p.Stack
        as={"div"}
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        hasGap={true}
        className={classNames(defaultcss.all, sty.box)}
      >
        {(hasVariant(variants, "stars", "zero") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__klTz3, {
              [sty.svg__stars_five__klTz3Iwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_zero__klTz3Lm64V]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? true
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__koRjv, {
              [sty.svg__stars_five__koRjviwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__koRjVn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__koRjv2CNu]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__koRjVfTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__koRjVwcrEe]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__koRjVlm64V]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? true
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__xIyGo, {
              [sty.svg__stars_five__xIyGoIwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__xIyGon9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__xIyGo2CNu]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__xIyGofTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__xIyGowcrEe]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__xIyGolm64V]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? true
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__uxTMw, {
              [sty.svg__stars_five__uxTMwIwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__uxTMwn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one__uxTMw2CNu]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three__uxTMwfTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__uxTMwwcrEe]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero__uxTMwlm64V]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? true
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? false
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___4QkEg, {
              [sty.svg__stars_five___4QkEgiwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four___4QkEGn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one___4QkEg2CNu]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three___4QkEGfTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two___4QkEGwcrEe]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero___4QkEGlm64V]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : hasVariant(variants, "stars", "one")
            ? false
            : hasVariant(variants, "stars", "zero")
            ? true
            : false
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___1SNyK, {
              [sty.svg__stars_five___1SNyKiwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four___1SNyKn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_one___1SNyK2CNu]: hasVariant(
                variants,
                "stars",
                "one"
              ),
              [sty.svg__stars_three___1SNyKfTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two___1SNyKwcrEe]: hasVariant(
                variants,
                "stars",
                "two"
              ),
              [sty.svg__stars_zero___1SNyKlm64V]: hasVariant(
                variants,
                "stars",
                "zero"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : hasVariant(variants, "stars", "two")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__c8Eup, {
              [sty.svg__stars_five__c8EupIwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__c8Eupn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__c8EupfTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              ),
              [sty.svg__stars_two__c8EupwcrEe]: hasVariant(
                variants,
                "stars",
                "two"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : hasVariant(variants, "stars", "three")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__qCpov, {
              [sty.svg__stars_five__qCpovIwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__qCpovn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              ),
              [sty.svg__stars_three__qCpovfTgPw]: hasVariant(
                variants,
                "stars",
                "three"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(
          hasVariant(variants, "stars", "five")
            ? false
            : hasVariant(variants, "stars", "four")
            ? false
            : true
        ) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg__xfz6H, {
              [sty.svg__stars_five__xfz6HIwj8]: hasVariant(
                variants,
                "stars",
                "five"
              ),
              [sty.svg__stars_four__xfz6Hn9Xy9]: hasVariant(
                variants,
                "stars",
                "four"
              )
            })}
            role={"img"}
          />
        ) : null}
        {(hasVariant(variants, "stars", "five") ? false : true) ? (
          <StarIcon
            className={classNames(defaultcss.all, sty.svg___0R4Ut, {
              [sty.svg__stars_five___0R4UtIwj8]: hasVariant(
                variants,
                "stars",
                "five"
              )
            })}
            role={"img"}
          />
        ) : null}
      </p.Stack>

      <p.PlasmicSlot
        defaultContents={"(45 Review)"}
        value={args.numReviews}
        className={classNames(sty.slotNumReviews)}
      />
    </p.Stack>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRatings__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicRatings__VariantsArgs;
  args?: PlasmicRatings__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicRatings__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicRatings__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRatings__ArgProps,
      internalVariantPropNames: PlasmicRatings__VariantProps
    });

    return PlasmicRatings__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRatings";
  } else {
    func.displayName = `PlasmicRatings.${nodeName}`;
  }
  return func;
}

export const PlasmicRatings = Object.assign(
  // Top-level PlasmicRatings renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicRatings
    internalVariantProps: PlasmicRatings__VariantProps,
    internalArgProps: PlasmicRatings__ArgProps
  }
);

export default PlasmicRatings;
/* prettier-ignore-end */
